name: build-android-r2-snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ubuntu:20.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git make clang wget gperf \
            cabextract unzip \
            python2 \
            pax file

      - name: Install legacy NDK r21d
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
          unzip -q android-ndk-r21d-linux-x86_64.zip
          export NDK=$PWD/android-ndk-r21d
          echo "NDK=$NDK" >> $GITHUB_ENV

      - name: Build Android snapshot style
        run: |
          export NDK=$NDK
          sys/android-build.sh aarch64

      - name: Extract r2
        run: |
          mkdir out
          tar -xzf radare2-*-android-aarch64*.tar.gz -C out
          cp $(find out -name r2 | head -n1) ./r2
          file r2

      - uses: actions/upload-artifact@v4
        with:
          name: r2-android-aarch64
          path: r2
